apiVersion: v1
kind: ReplicationController
metadata:
  name:  myvertexapp-rc
spec:
   replicas: 2
   selector: 
     app:  myvertexapp
   template:                                     
     metadata:
       labels:
          app:  myvertexapp
     spec:
        containers:
        - name:  myvertexapp-container
          image: nbktechnosys/myverteximage10mar23:1
          ports:
          - containerPort: 8080 