
apiVersion: v1
kind: Service
metadata:
  name: myvertexapp-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080   # Ensure the targetPort is correctly mapped to the pod's container port
      nodePort: 30001
      protocol: TCP
  selector:
    app: myvertexapp
