apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlineapp-rc
spec:
   replicas: 3
   selector: 
     app: myonlineapp
     version: 2.6.1
   template:                                     
     metadata:
       labels:
          app: myonlineappss
          version: 2.6.1
     spec:
        containers:
        - name: myonlineapp-container
          image: nbktechnosys/myjavaimages2dec22:1
          ports:
          - containerPort: 8080 