apiVersion: apps/v1
kind: Deployment
metadata:
  name: myonlineapp-deploy
  labels:
    app: myonlineapp
spec:
  replicas: 3
  selector:
      matchLabels:
         app: myonlineapp
  template:
     metadata:
       labels: 
         app: myonlineapp
     spec:
       containers:
        - name: myvertexapp-container
          image: nbktechnosys/myjavaimages1dec22:1
          ports:
            - containerPort: 8080